[settings]
animate = true
animation_duration = 0.3
animation_fps = 120.0
animation_easing = "ease_out_quint"
default_disable = false
focus_follows_mouse = false
mouse_follows_focus = true
mouse_hides_on_focus = false
auto_focus_blacklist = []
run_on_start = []
hot_reload = true

[settings.layout]
mode = "scrolling"
window_insertion_point = "next_to_selection"

[settings.layout.scrolling]
column_width_ratio = 1.0
preserve_window_sizes = false
min_column_width_ratio = 0.25
max_column_width_ratio = 1.0
alignment = "center"
focus_navigation_style = "niri"

[settings.layout.gaps.outer]
top = 4
left = 4
bottom = 4
right = 4

[settings.layout.gaps.inner]
horizontal = 4
vertical = 4

[settings.ui.menu_bar]
enabled = false
show_empty = false
mode = "all"
active_label = "index"
display_style = "layout"

[settings.gestures]
enabled = false

[settings.drag_drop]
enabled = true
action1 = "none"
drop_action = "swap"
drop_zone_fraction = 0.25
preview = false

[virtual_workspaces]
enabled = false
default_workspace_count = 1
workspace_names = ["Main"]

[keys]
"Alt + H" = { move_focus = "left" }
"Alt + L" = { move_focus = "right" }
"Alt + Shift + H" = { move_node = "left" }
"Alt + Shift + L" = { move_node = "right" }
"Alt + F" = "toggle_fullscreen_within_gaps"
"Alt + T" = { toggle_window_floating = { center = true } }
"Alt + R" = { binding_mode = "resize" }

[binding_modes.resize]
"L" = { resize_window_grow = "horizontal" }
"H" = { resize_window_shrink = "horizontal" }
"Escape" = { binding_mode = "default" }
