#!/usr/bin/env sh

options=(
    style=round
    active_color="gradient(top_left=0xFFC7F5FF,bottom_right=0xFF5DAEFF)"
    inactive_color="gradient(top_left=0xAA6F86A3,bottom_right=0xAA3D536B)"
    width=6.0
    hidpi=on
    blacklist=
)

borders "${options[@]}"
