# outputs.nix — the actual outputs function, loaded from the generated flake.nix
# via `outputs = inputs: import ./outputs.nix inputs`.
#
# This file is imported by flake.nix (generated by flake-file) and contains the
# blueprint launcher plus the custom output attributes that blueprint does not
# discover automatically.
inputs:
let
  cache = import ./nix/r2-cache.nix;

  systems = [
    "aarch64-darwin"
    "x86_64-linux"
  ];

  blueprint = inputs.blueprint {
    inherit inputs;
    prefix = "nix/";
    inherit systems;

    nixpkgs = {
      config.allowUnfree = true;
      overlays = import ./nix/overlays;
    };
  };

  # Evaluate the flake-file module so the `write-flake` app stays available
  # after flake.nix is regenerated (the generated flake.nix delegates outputs
  # to this file).
  flake-file-eval = import ./flake-file.nix { inherit inputs; };

  # flake-file apps are functions `pkgs: <drv>`; convert them to the flake
  # `app` type (`{ type = "app"; program = <path>; }`) per system.
  flake-file-apps = inputs.nixpkgs.lib.genAttrs systems (
    system:
    let
      pkgs = inputs.nixpkgs.legacyPackages.${system};
    in
    builtins.mapAttrs
      (name: app: {
        type = "app";
        program = "${app pkgs}/bin/${name}";
      })
      flake-file-eval.config.flake-file.apps
  );
in
blueprint
// {
  apps = (blueprint.apps or { }) // flake-file-apps;

  cacheSettings = cache;

  configurationBuilds = {
    macbook-pro.system =
      blueprint.darwinConfigurations.macbook-pro.config.system.build.toplevel;

    ubuntu-wsl = {
      system = blueprint.systemConfigs.ubuntu-wsl;
      home =
        blueprint.legacyPackages.x86_64-linux.homeConfigurations
          ."k0ch4nx@ubuntu-wsl"
          .activationPackage;
    };
  };

  darwinConfigurations = blueprint.darwinConfigurations // {
    cache-bootstrap = inputs.nix-darwin.lib.darwinSystem {
      modules = [ ./nix/cache-bootstrap/darwin.nix ];
      specialArgs = {
        flake = inputs.self;
        inherit inputs;
        hostName = "macbook-pro";
      };
    };
  };

  systemConfigs = blueprint.systemConfigs // {
    cache-bootstrap = inputs.system-manager.lib.makeSystemConfig {
      modules = [ ./nix/cache-bootstrap/wsl.nix ];
      extraSpecialArgs = {
        flake = inputs.self;
        inherit inputs;
        hostName = "ubuntu-wsl";
      };
    };
  };

  homeConfigurations."k0ch4nx@ubuntu-wsl" =
    blueprint.legacyPackages.x86_64-linux.homeConfigurations."k0ch4nx@ubuntu-wsl";

  agenix-rekey =
    (inputs.agenix-rekey.configure {
      userFlake = inputs.self;

      darwinConfigurations = {
        inherit (inputs.self.darwinConfigurations) cache-bootstrap macbook-pro;
      };

      systems = [
        "aarch64-darwin"
      ];
    })
    // (inputs.agenix-rekey.configure {
      userFlake = inputs.self;

      nixosConfigurations = {
        inherit (inputs.self.systemConfigs) cache-bootstrap ubuntu-wsl;
      };

      homeConfigurations = {
        inherit (inputs.self.homeConfigurations) "k0ch4nx@ubuntu-wsl";
      };

      systems = [
        "x86_64-linux"
      ];
    });
}
