[options]
focus_follows_mouse = false
mouse_follows_focus = true
animation_speed = 12.0

[padding]
top = 4
bottom = 4
left = 4
right = 4

[swipe.scroll]
modifier = "alt"

[decorations]
workspace_menu_status = true

[decorations.active.border]
enabled = true
color = "#F04A00"
width = 3.0
radius = "auto"

[restore]
enabled = true

[bindings]
window_focus_west = "alt - h"
window_focus_east = "alt - l"
window_swap_west = "alt + shift - h"
window_swap_east = "alt + shift - l"
window_fullwidth = "alt - f"
window_manage = "alt - t"
window_resize = "alt - r"

[windows.defaults]
title = ".*"
width = 1.0
horizontal_padding = 4
vertical_padding = 4

[windows.steam]
bundle_id = "com.valvesoftware.steam"
title = ".*"
manage = true

[windows.iina]
bundle_id = "com.colliderli.iina"
title = ".*"
floating = true
