[misc]
no_retry = true
only = [
  "custom_commands",
  "system",
]

[include]
# Topgrade executes included command tables in reverse merge order.
paths = [
  "~/.config/topgrade/includes/common/neovim.toml",
  "~/.config/topgrade/includes/host/system.toml",
  "~/.config/topgrade/includes/common/nix.toml",
]
