{ inputs, pkgs, ... }:
{
  home.packages = with pkgs; [
    _010editor
    inputs.agenix.packages.${pkgs.stdenv.hostPlatform.system}.default
    apparency
    azahar
    betterdisplay
    blender
    discord
    dolphin-emu
    fabric-installer
    ferium
    ghidra
    google-chrome
    iina
    jankyborders
    lmstudio
    mas
    mcat
    orbstack
    ryubing
    sheets
    snitch
    superseedr
    terminal-browser
    udev-gothic-nf
    wezterm
  ];
}
