{ inputs, pkgs, ... }:
{
  home.packages = with pkgs; [
    _010editor
    inputs.agenix.packages.${pkgs.stdenv.hostPlatform.system}.default
    age-plugin-yubikey
    apparency
    aria2
    asciinema
    azahar
    bacon
    bazelisk
    betterdisplay
    blender
    bottom
    bun
    cloudflared
    cmake
    commitizen
    discord
    dolphin-emu
    dotnet-sdk_10
    fabric-installer
    fastfetch
    ferium
    ffmpeg-full
    gh
    ghidra
    git-cliff
    gitlogue
    google-chrome
    google-cloud-sdk
    gradle
    haiti
    hashcat
    hyperfine
    iina
    imagemagick
    jankyborders
    john
    lazygit
    lmstudio
    mas
    mpv
    nixfmt
    nodejs_latest
    oh-my-posh
    onefetch
    opencode
    openssh
    orbstack
    progress
    python314
    python3Packages.huggingface-hub
    python3Packages.lizard
    qbittorrent
    rage
    rustup
    ryubing
    skhd
    temurin-bin-25
    terraform
    tokei
    tree-sitter
    udev-gothic-nf
    vscode
    wezterm
    yabai
    yubikey-manager
    zig
    zsh-fzf-tab
  ];
}
