# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Rebase Pull Requests

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  rebase:
    name: Rebase open pull requests
    runs-on: ubuntu-latest

    steps:
      - name: Rebase pull requests onto main
        uses: peter-evans/rebase@e4945786f7ca41fe6e101cead4395f5489593943 # v4
        with:
          base: main
          exclude-drafts: true
